# Generated by Django 3.0.5 on 2020-09-23 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(blank=True, max_length=30, null=True)),
                ('job_category', models.CharField(choices=[('G', 'Government'), ('IT', 'IT & Telecommunication'), ('H', 'Hospitality'), ('AM', 'Administration/Management'), ('NI', 'NGO/INGO'), ('T', 'Teaching/Education'), ('Ar', 'Architecture/Interior Design'), ('S', 'Sales/Public Relation')], max_length=6)),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=30, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('openings', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('hours', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('description', models.FileField(upload_to='description/')),
                ('job_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Apply.Job')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('mname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('contact', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateTimeField()),
                ('resume', models.FileField(upload_to='resume/')),
                ('jobID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apply.Job')),
                ('userID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
