# Generated by Django 3.0.5 on 2020-10-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosine_similarity', models.FloatField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Apply.EmployeeApplicants')),
                ('job_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Apply.Job')),
            ],
        ),
    ]
