# Generated by Django 3.1.1 on 2020-12-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0004_employeeapplicants_aptitude_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeapplicants',
            name='aptitude_score',
            field=models.IntegerField(default=0),
        ),
    ]
