# Generated by Django 3.1.1 on 2021-02-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apply', '0005_auto_20201213_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('desc1', models.IntegerField()),
                ('desc2', models.IntegerField()),
                ('desc3', models.IntegerField()),
            ],
        ),
    ]
